apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sample-app
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 100
      containers:
      - image: gcr.io/knative-samples/helloworld-go:latest
        ports:
        - containerPort: 6000
        resources:
          limits:
            memory: 256Mi
            cpu: 100m
