apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: devops-toolkit-test
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 100
      containers:
      - image: vfarcic/devops-toolkit-series
        env:

        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 256Mi
            cpu: 100m
